=== bmjoy/centurion/centurion-source/assets/xml-schemas/characters.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="chars">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="char">
          <xs:complexType>
            <xs:attribute name="id" type="xs:integer" use="required" />
            <xs:attribute name="x" type="xs:integer" use="required" />
            <xs:attribute name="y" type="xs:integer" use="required" />
            <xs:attribute name="width" type="xs:integer" use="required" />
            <xs:attribute name="height" type="xs:integer" use="required" />
            <xs:attribute name="xoffset" type="xs:integer" use="required" />
            <xs:attribute name="yoffset" type="xs:integer" use="required" />
            <xs:attribute name="xadvance" type="xs:integer" use="required" />
            <xs:attribute name="lineheight" type="xs:integer" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bmjoy/centurion/centurion-source/assets/xml-schemas/characters.xml
<chars name="arabic_16px" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml-schemas/characters.xsd">
	<char id="32" x="6" y="294" width="5" height="20" xoffset="0" yoffset="0" xadvance="10" lineheight="19" />
	<char id="33" x="314" y="273" width="6" height="20" xoffset="0" yoffset="0" xadvance="5" lineheight="19" />
	<char id="34" x="230" y="273" width="6" height="20" xoffset="0" yoffset="0" xadvance="5" lineheight="19" />
	<char id="35" x="139" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="36" x="239" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="37" x="47" y="63" width="14" height="20" xoffset="0" yoffset="0" xadvance="13" lineheight="19" />
	<char id="38" x="91" y="63" width="13" height="20" xoffset="0" yoffset="0" xadvance="12" lineheight="19" />
	<char id="39" x="197" y="294" width="4" height="20" xoffset="0" yoffset="0" xadvance="3" lineheight="19" />
	<char id="40" x="415" y="231" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="41" x="487" y="231" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="42" x="249" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="43" x="0" y="147" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="44" x="454" y="273" width="5" height="20" xoffset="0" yoffset="0" xadvance="4" lineheight="19" />
	<char id="45" x="495" y="231" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="46" x="448" y="273" width="5" height="20" xoffset="0" yoffset="0" xadvance="4" lineheight="19" />
	<char id="47" x="503" y="231" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="48" x="279" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="49" x="289" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="50" x="319" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="51" x="339" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="52" x="349" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="53" x="399" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="54" x="409" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="55" x="429" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="56" x="439" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="57" x="449" y="189" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="58" x="232" y="294" width="4" height="20" xoffset="0" yoffset="0" xadvance="3" lineheight="19" />
	<char id="59" x="442" y="273" width="5" height="20" xoffset="0" yoffset="0" xadvance="4" lineheight="19" />
	<char id="60" x="187" y="147" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="61" x="198" y="147" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="62" x="77" y="189" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="63" x="162" y="231" width="8" height="20" xoffset="0" yoffset="0" xadvance="7" lineheight="19" />
	<char id="64" x="173" y="21" width="16" height="20" xoffset="0" yoffset="0" xadvance="15" lineheight="19" />
	<char id="123" x="144" y="231" width="8" height="20" xoffset="0" yoffset="0" xadvance="7" lineheight="19" />
	<char id="124" x="242" y="294" width="4" height="20" xoffset="0" yoffset="0" xadvance="3" lineheight="19" />
	<char id="125" x="360" y="210" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="126" x="471" y="105" width="11" height="20" xoffset="0" yoffset="0" xadvance="10" lineheight="19" />
	<char id="1536" x="241" y="21" width="16" height="20" xoffset="0" yoffset="0" xadvance="15" lineheight="19" />
	<char id="1537" x="58" y="0" width="22" height="20" xoffset="0" yoffset="0" xadvance="21" lineheight="19" />
	<char id="1538" x="483" y="105" width="11" height="20" xoffset="0" yoffset="0" xadvance="10" lineheight="19" />
	<char id="1539" x="104" y="0" width="21" height="20" xoffset="0" yoffset="0" xadvance="20" lineheight="19" />
	<char id="1540" x="81" y="0" width="22" height="20" xoffset="0" yoffset="0" xadvance="21" lineheight="19" />
	<char id="1541" x="495" y="105" width="11" height="20" xoffset="0" yoffset="0" xadvance="10" lineheight="19" />
	<char id="1542" x="0" y="126" width="11" height="20" xoffset="0" yoffset="0" xadvance="10" lineheight="19" />
	<char id="1543" x="12" y="126" width="11" height="20" xoffset="0" yoffset="0" xadvance="10" lineheight="19" />
	<char id="1544" x="62" y="63" width="14" height="20" xoffset="0" yoffset="0" xadvance="13" lineheight="19" />
	<char id="1545" x="24" y="126" width="11" height="20" xoffset="0" yoffset="0" xadvance="10" lineheight="19" />
	<char id="1546" x="315" y="63" width="13" height="20" xoffset="0" yoffset="0" xadvance="12" lineheight="19" />
	<char id="1547" x="0" y="252" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="1548" x="111" y="273" width="6" height="20" xoffset="0" yoffset="0" xadvance="5" lineheight="19" />
	<char id="1549" x="83" y="273" width="6" height="20" xoffset="0" yoffset="0" xadvance="5" lineheight="19" />
	<char id="1550" x="32" y="63" width="14" height="20" xoffset="0" yoffset="0" xadvance="13" lineheight="19" />
	<char id="1551" x="385" y="168" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="1552" x="8" y="252" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="1553" x="430" y="273" width="5" height="20" xoffset="0" yoffset="0" xadvance="4" lineheight="19" />
	<char id="1554" x="16" y="252" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="1555" x="210" y="210" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="1556" x="198" y="231" width="8" height="20" xoffset="0" yoffset="0" xadvance="7" lineheight="19" />
	<char id="1557" x="24" y="252" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="1558" x="90" y="231" width="8" height="20" xoffset="0" yoffset="0" xadvance="7" lineheight="19" />
	<char id="1559" x="328" y="273" width="6" height="20" xoffset="0" yoffset="0" xadvance="5" lineheight="19" />
	<char id="1560" x="107" y="294" width="4" height="20" xoffset="0" yoffset="0" xadvance="3" lineheight="19" />
	<char id="1561" x="424" y="273" width="5" height="20" xoffset="0" yoffset="0" xadvance="4" lineheight="19" />
	<char id="1562" x="112" y="294" width="4" height="20" xoffset="0" yoffset="0" xadvance="3" lineheight="19" />
	<char id="1563" x="300" y="273" width="6" height="20" xoffset="0" yoffset="0" xadvance="5" lineheight="19" />
	<char id="1564" x="336" y="0" width="19" height="20" xoffset="0" yoffset="0" xadvance="18" lineheight="19" />
	<char id="1566" x="293" y="273" width="6" height="20" xoffset="0" yoffset="0" xadvance="5" lineheight="19" />
	<char id="1567" x="32" y="252" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="1568" x="84" y="126" width="11" height="20" xoffset="0" yoffset="0" xadvance="10" lineheight="19" />
	<char id="1569" x="135" y="231" width="8" height="20" xoffset="0" yoffset="0" xadvance="7" lineheight="19" />
	<char id="1570" x="286" y="273" width="6" height="20" xoffset="0" yoffset="0" xadvance="5" lineheight="19" />
	<char id="1571" x="132" y="294" width="4" height="20" xoffset="0" yoffset="0" xadvance="3" lineheight="19" />
	<char id="1572" x="160" y="210" width="9" height="20" xoffset="0" yoffset="0" xadvance="8" lineheight="19" />
	<char id="1573" x="177" y="294" width="4" height="20" xoffset="0" yoffset="0" xadvance="3" lineheight="19" />
	<char id="1574" x="108" y="126" width="11" height="20" xoffset="0" yoffset="0" xadvance="10" lineheight="19" />
	<char id="1575" x="187" y="294" width="4" height="20" xoffset="0" yoffset="0" xadvance="3" lineheight="19" />
	<char id="1576" x="441" y="63" width="13" height="20" xoffset="0" yoffset="0" xadvance="12" lineheight="19" />
	<char id="1577" x="40" y="252" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="1578" x="399" y="63" width="13" height="20" xoffset="0" yoffset="0" xadvance="12" lineheight="19" />
	<char id="1579" x="385" y="63" width="13" height="20" xoffset="0" yoffset="0" xadvance="12" lineheight="19" />
	<char id="1580" x="330" y="168" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="1581" x="319" y="168" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="1582" x="308" y="168" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="1583" x="48" y="252" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="1584" x="56" y="252" width="7" height="20" xoffset="0" yoffset="0" xadvance="6" lineheight="19" />
	<char id="1585" x="297" y="168" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="1586" x="286" y="168" width="10" height="20" xoffset="0" yoffset="0" xadvance="9" lineheight="19" />
	<char id="1587" x="16" y="63" width="15" height="20" xoffset="0" yoffset="0" xadvance="14" lineheight="19" />
	<char id="1588" x="411" y="21" width="15" height="20" xoffset="0" yoffset="0" xadvance="14" lineheight="19" />
