=== bmjoy/centurion/centurion-source/assets/xml-schemas/entity.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="c_entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="properties">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="property">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:integer" use="required"/>
                  <xs:attribute name="value" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="points">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="point">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:integer" use="required"/>
                  <xs:attribute name="type" type="xs:integer" use="required"/>
                  <xs:attribute name="x" type="xs:integer" use="required"/>
                  <xs:attribute name="y" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="images">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="image">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:integer" use="required"/>
                  <xs:attribute name="file" type="xs:string" use="required"/>
                  <xs:attribute name="drawmode" type="xs:string" use="required"/>
                  <xs:attribute name="reverse" type="xs:boolean" use="required"/>
                  <xs:attribute name="frames" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="layers">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="layer">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:integer" use="required"/>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="image" type="xs:integer" use="required"/>
                  <xs:attribute name="x" type="xs:integer" use="required"/>
                  <xs:attribute name="y" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="animations">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="animation">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="replace">
                      <xs:complexType>
                        <xs:attribute name="layer" type="xs:integer" use="required"/>
                        <xs:attribute name="image" type="xs:integer" use="required"/>
                        <xs:attribute name="x" type="xs:integer" use="required"/>
                        <xs:attribute name="y" type="xs:integer" use="required"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element maxOccurs="unbounded" name="frame">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                        <xs:attribute name="milliseconds" type="xs:integer" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:integer" use="required"/>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="startstate" type="xs:integer" use="required"/>
                  <xs:attribute name="endstate" type="xs:integer" use="required"/>
                  <xs:attribute name="frames" type="xs:integer" use="required"/>
                  <xs:attribute name="speedMultiplier" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="directions" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bmjoy/centurion/centurion-source/assets/xml-schemas/entity.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<c_entity type="unit" directions="8" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml-schemas/entity.xsd">
	<properties>
		<property name="firstAttackFrame" value="4"/>
		<property name="secondAttackFrame" value="8"/>
	</properties>
	<points>
		<point id="0" type="5" x="63" y="19"/>
		<point id="1" type="7" x="72" y="58"/>
	</points>
	<images>
		<image id="0" file="Idle" drawmode="colors" reverse="false" frames="7"/>
		<image id="1" file="Idle_shadow" drawmode="shadow" reverse="false" frames="7"/>
		<image id="2" file="Walk" drawmode="colors" reverse="false" frames="10"/>
		<image id="3" file="Walk_shadow" drawmode="shadow" reverse="false" frames="10"/>
	</images>
	<layers>
		<layer id="0" name="Unit" image="0" x="0" y="0"/>
		<layer id="1" name="Shadow" image="1" x="-24" y="-24"/>
	</layers>
	<animations>
		<animation id="0" name="Idle" startstate="1" endstate="1" frames="7" speedMultiplier="1">
		<replace layer="0" image="0" x="0" y="0"/>
		<replace layer="1" image="1" x="-24" y="-24"/>
		<frame id="0" milliseconds="53"/>
		<frame id="1" milliseconds="53"/>
		<frame id="2" milliseconds="53"/>
		<frame id="3" milliseconds="53"/>
		<frame id="4" milliseconds="53"/>
		<frame id="5" milliseconds="53"/>
		<frame id="6" milliseconds="53"/>
		</animation>
		<animation id="1" name="Walk" startstate="1" endstate="1" frames="10" speedMultiplier="1">
		<replace layer="0" image="2" x="0" y="0"/>
		<replace layer="1" image="3" x="-24" y="-24"/>
		<frame id="0" milliseconds="53"/>
		<frame id="1" milliseconds="53"/>
		<frame id="2" milliseconds="53"/>
		<frame id="3" milliseconds="53"/>
		<frame id="4" milliseconds="53"/>
		<frame id="5" milliseconds="53"/>
		<frame id="6" milliseconds="53"/>
		<frame id="7" milliseconds="53"/>
		<frame id="8" milliseconds="53"/>
		<frame id="9" milliseconds="53"/>
		</animation>
	</animations>
</c_entity>
