=== bmjoy/centurion/centurion-source/assets/xml-schemas/object.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="c_object">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="properties">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="property">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="value" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="methods">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0"  maxOccurs="unbounded" name="method">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="script" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="sounds">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0"  maxOccurs="unbounded" name="sound">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="path" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="parent" type="xs:string" use="required" />
      <xs:attribute name="type" type="xs:string" use="required" />
      <xs:attribute name="class_name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bmjoy/centurion/centurion-source/assets/data/classes_new/hmyrmidon.oc.xml
<c_object parent="Ranged" type="unit" class_name="HMyrmidon" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Object.xsd">
 <properties>
    <property name="minAttack" value="10"/>
    <property name="maxAttack" value="30"/>
    <property name="maxhealth" value="200"/>
    <property name="speed" value="50"/>
    <property name="ent_path" value="assets/units/hmyrmidon/hmyrmidon.oe.json"/>
  </properties>
  <methods>
    <method name="" script=""/>
  </methods>
  <sounds>
    <sound name="" path=""/>
  </sounds>
</c_object>

=== bmjoy/centurion/centurion-source/assets/data/classes_new/jasmimmanga.oc.xml
<c_object parent="Object" type="decoration" class_name="Jasmimmanga" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Object.xsd">
 <properties>
    <property name="category" value="trees"/>
    <property name="ent_path" value="assets/decorations/trees/tropicals/jasmimmanga.oe.json"/>
    <property name="pass_path" value="assets/decorations/trees/tropicals/jasmimmanga.pass"/>
  </properties>
  <methods>
    <method name="" script=""/>
  </methods>
  <sounds>
    <sound name="" path=""/>
  </sounds>
</c_object>

=== bmjoy/centurion/centurion-source/assets/data/classes_new/etavern.oc.xml
<c_object parent="Building" type="building" class_name="ETavern" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Object.xsd">
 <properties>
    <property name="race" value="Egypt"/>
    <property name="radius" value="1000"/>
    <property name="isCentralBuilding" value="0"/>
    <property name="category" value="egyptianstronghold"/>
    <property name="ent_path" value="assets/buildings/egypt/tavern/etavern.oe.json"/>
    <property name="pass_path" value="assets/buildings/egypt/tavern/etavern.pass"/>
    <property name="clickable_in_minimap" value="0"/>
  </properties>
  <methods>
    <method name="" script=""/>
  </methods>
  <sounds>
    <sound name="select" path="sounds/eTavernSelect.ogg"/>
  </sounds>
</c_object>

=== bmjoy/centurion/centurion-source/assets/data/classes_new/cypress.oc.xml
<c_object parent="Object" type="decoration" class_name="Cypress" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xml-schemas/Object.xsd">
 <properties>
    <property name="category" value="trees"/>
    <property name="ent_path" value="assets/decorations/trees/pine_trees/cypress.oe.json"/>
    <property name="pass_path" value="assets/decorations/trees/pine_trees/cypress.pass"/>
  </properties>
  <methods>
    <method name="" script=""/>
  </methods>
  <sounds>
    <sound name="" path=""/>
  </sounds>
</c_object>
