=== bmjoy/centurion/centurion-source/source/xmlSchemas/mapObjects.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="c_mapObjects">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="object">
          <xs:complexType>
            <xs:attribute name="class" type="xs:string" use="required" />
            <xs:attribute name="id" type="xs:integer" use="required" />
            <xs:attribute name="healthperc" type="xs:integer" use="optional" />
            <xs:attribute name="player" type="xs:integer" use="required" />
            <xs:attribute name="x" type="xs:integer" use="required" />
            <xs:attribute name="y" type="xs:integer" use="required" />
            <xs:attribute name="name" type="xs:string" use="optional" />
            <xs:attribute name="icon" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="settlement">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="object">
                <xs:complexType>
					<xs:attribute name="class" type="xs:string" use="required" />
					<xs:attribute name="id" type="xs:integer" use="required" />
					<xs:attribute name="healthperc" type="xs:integer" use="optional" default="100" />
					<xs:attribute name="player" type="xs:integer" use="required" />
					<xs:attribute name="x" type="xs:integer" use="required" />
					<xs:attribute name="y" type="xs:integer" use="required" />
					<xs:attribute name="name" type="xs:string" use="optional" />
					<xs:attribute name="icon" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="class" type="xs:string" use="required" />
            <xs:attribute name="id" type="xs:integer" use="required" />
            <xs:attribute name="player" type="xs:integer" use="required" />
            <xs:attribute name="x" type="xs:integer" use="required" />
            <xs:attribute name="y" type="xs:integer" use="required" />
            <xs:attribute name="name" type="xs:string" use="optional" />
            <xs:attribute name="gold" type="xs:integer" use="optional" default="0" />
            <xs:attribute name="food" type="xs:integer" use="optional" default="0" />
            <xs:attribute name="population" type="xs:integer" use="optional" />
            <xs:attribute name="maxpopulation" type="xs:integer" use="optional" />
            <xs:attribute name="healthperc" type="xs:integer" use="optional" default="100" />
            <xs:attribute name="icon" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bmjoy/centurion/centurion-source/assets/xml-schemas/mapObjects.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<c_mapObjects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mapObjects.xsd">
	<object class="class_placeholder" id="1" healthperc="100" player="1" x="100" y="200" name="ciao" icon="ciao"/>
    <object class="class_placeholder" id="2" healthperc="100" player="2" x="100" y="200" name="ciao" icon="ciao" />
	<settlement class="RTownhall" id="3" player="1" x="100" y="200" name="ciao" gold="100" food="100" population="100" maxpopulation="200" healthperc="100" icon="ciao">
        <object class="class_placeholder" id="4" healthperc="100" player="1" x="100" y="200" icon="ciao" />
        <object class="class_placeholder" id="5" healthperc="100" player="1" x="100" y="200" icon="ciao" />
    </settlement>
    <settlement class="RTownhall" id="6" player="1" x="100" y="200" name="ciao" gold="100" food="100" population="100" maxpopulation="200" healthperc="100" icon="ciao">
        <object class="class_placeholder" id="7" healthperc="100" player="1" x="100" y="200" icon="ciao" />
        <object class="class_placeholder" id="8" healthperc="100" player="1" x="100" y="200" icon="ciao" />
    </settlement>
</c_mapObjects>
